name: Generate Statistics
on: push

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate statistics
        uses: jojo2357/Code-Stats-Action@0.4.1
        with:
          root_dir: src/main
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          branch: ${{ github.head_ref }}
          commit_message: Woooooooooo stats
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          push_options: --force